"""Zero-Set Forward Light Tracing research prototype."""

from .camera import PlanarCamera
from .fields import (
    LocalBasisField,
    SphereField,
    TorusField,
    ZeroSetField,
    deform_reference_surface,
    implicit_position_jacobian,
    unit_normals,
)
from .tracer import (
    PhotonBatch,
    RenderResult,
    TraceResult,
    emit_photons,
    first_zero_set_intersections,
    make_scene,
    render_first_arrival,
    trace_photons,
)
from .jacobian import (
    FixedTransportCell,
    GeometryJacobian,
    build_fixed_transport_cell,
    deterministic_directions,
    exact_deformation,
    finite_difference_report,
    geometry_image_jacobian,
    locality_perturbation_report,
    make_local_basis_field,
    observability_report,
    render_fixed_transport_cell,
    sparse_bilinear_transport,
    sparse_geometry_image_jacobian,
    support_report,
    topology_event_pixels,
)
from .benchmark import (
    RESOLUTION_SWEEP,
    benchmark_cpu_reference,
    benchmark_cuda_resolution,
    cuda_environment,
    cuda_equivalence_report,
)
from .birth import (
    BirthConfig,
    KScalingConfig,
    run_birth_experiment,
    run_k_scaling_experiment,
)
from .multiview import (
    CAMERA_COUNTS,
    CameraTransport,
    MultiviewConfig,
    SceneTransportState,
    build_scene_transport,
    multiview_cameras,
    multiview_cpu_verification,
    project_camera,
    run_multiview_benchmark,
    validate_multiview_equivalence,
)
from .locality import locality_cpu_verification

__all__ = [
    "PhotonBatch",
    "PlanarCamera",
    "RenderResult",
    "LocalBasisField",
    "SphereField",
    "TorusField",
    "TraceResult",
    "ZeroSetField",
    "emit_photons",
    "deform_reference_surface",
    "first_zero_set_intersections",
    "implicit_position_jacobian",
    "make_scene",
    "render_first_arrival",
    "trace_photons",
    "unit_normals",
    "FixedTransportCell",
    "GeometryJacobian",
    "build_fixed_transport_cell",
    "deterministic_directions",
    "exact_deformation",
    "finite_difference_report",
    "geometry_image_jacobian",
    "locality_perturbation_report",
    "make_local_basis_field",
    "observability_report",
    "render_fixed_transport_cell",
    "sparse_bilinear_transport",
    "sparse_geometry_image_jacobian",
    "support_report",
    "topology_event_pixels",
    "RESOLUTION_SWEEP",
    "benchmark_cpu_reference",
    "benchmark_cuda_resolution",
    "cuda_environment",
    "cuda_equivalence_report",
    "BirthConfig",
    "KScalingConfig",
    "run_birth_experiment",
    "run_k_scaling_experiment",
    "CAMERA_COUNTS",
    "CameraTransport",
    "MultiviewConfig",
    "SceneTransportState",
    "build_scene_transport",
    "multiview_cameras",
    "multiview_cpu_verification",
    "project_camera",
    "run_multiview_benchmark",
    "validate_multiview_equivalence",
    "locality_cpu_verification",
]
